[package]
name = "worktree-git-gix"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
benchmarks = ["worktree-core/benchmarks"]

[dependencies]
worktree-core = { workspace = true }
gix = { workspace = true }
rust-i18n = { workspace = true }
rustc-hash = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
worktree-core = { workspace = true, features = ["test-support", "benchmarks"] }
syn = { version = "3", features = ["full", "visit"] }
worktree-test-support = { workspace = true }
