[package]
name = "worktree-state"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
benchmarks = []
test-support = []

[dependencies]
worktree-core = { workspace = true }
gix = { workspace = true }
notify = { workspace = true }
rust-i18n = { workspace = true }
smol = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
worktree-core = { workspace = true, features = ["test-support"] }
worktree-git-gix = { workspace = true }
worktree-test-support = { workspace = true }
